CREATE SEQUENCE IF NOT EXISTS display_id_seq START WITH 1;

CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    display_id VARCHAR(60) UNIQUE NOT NULL DEFAULT ('u' || nextval('display_id_seq')::text),
    name VARCHAR(60) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    profile_avatar TEXT,
    session_last_seq INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pgp_profile (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    public_key TEXT NOT NULL,
    auth_key TEXT NOT NULL
);

CREATE TABLE session (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    seq INTEGER NOT NULL,
    alpha_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    beta_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message_last_seq INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE message (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    seq INTEGER NOT NULL UNIQUE,
    session_id BIGINT NOT NULL REFERENCES session(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    profile VARCHAR(15) NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
);